
service: photomosiac-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-west-2

package:
  exclude:
   - venv/**
   - node_modules/**
   - .serverless/
   - input_images/**
   - tests/**
   - blep.jpg

functions:

  mosaic:
    handler: app.handler.handler
    memorySize: 1000
    timeout: 60
    events:
      - http:
        cors: true
    layers: 
      - { Ref: PythonRequirementsLambdaLayer }
    environment:
      IMAGE_API_TOKEN: ${env: IMAGE_API_TOKEN}

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    layer: true
